### PR TITLE
Upgrade docker version

### PR DESCRIPTION
**Pull request by telphan**
Signed-off-by: Theodor Gherzan <theodor@balena.io>

### CODE REVIEW

**Comment by telphan** [comment]
@balena-ci retest

**Comment by telphan** [comment]
@balena-ci retest

**Comment by telphan** [comment]
@balena-ci retest

**Comment by telphan** [comment]
@balena-ci retest

**Comment by nazrhom** [comment]
@telphan this repo hasn't been updated in a while, at one point the node-cli check was activated on several repos by accident, I guess this is one of them that we haven't updated yet. Same fix applies here: merge as admin and the check will be removed by VB as the preconditions for the `node-cli` type do not apply

**Pull request merged**
