### PR TITLE
Bind mount host's /etc/ssl/certs folder on Linux

### PR DESCRIPTION
**Pull request by zvin**
Connects-to: #194 
Change-type: minor

### CODE REVIEW

**Comment by zvin** [comment]
@dfunckt 
The preloader container should trust the certificates from the host os. As a user I would expect this behaviour.
This isn't cross-platform, I'd like to find a way to make it so. This PR is a quick fix for the user that encountered the problem.
Adding the host's certificates in the preloader container is more complicated on Windows and macOS.

As for passing certificates explicitly, I've found this https://docs.docker.com/engine/security/certificates/ .
Implementation will be difficult. If we ask the user for a `.pem`, we need to extract the `.crt` and the domain name from it and place it into `/etc/docker/certs.d/DOMAIN/ca.crt`.

**Comment by dfunckt** [comment]
I see. I think though that Docker simply ignores the system cert store and just uses its own so the mount like you do here won't work, isn't that right?

**Comment by dfunckt** [comment]
I may be misremembering though and what I say only apply to Docker for Mac and the VM it launches in the background.

**Comment by zvin** [comment]
@dfunckt I just checked bind mounting an empty folder at `/etc/ssl/certs` in the preloader container. I get this error:
`(HTTP code 500) server error - Get https://registry2.balena-cloud.com/v2/: x509: failed to load system roots and no roots provided`
which means that `dockerd` uses system certs.

**Comment by dfunckt** [comment]
Perfect, thanks for confirming and also coming up with a fix so fast in the first place @zvin !

**Pull request merged**
